# YAPI DİNAMİĞİ ÇALIŞTAYI 2019
### İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ 9-19 EYLÜL 2019
#### Hazırlayan : Ahmet Anıl Dindar (adindar@gtu.edu.tr)

---

## __02. Python'da İşlemler :__ 

### 02.1- Döngüler
Python'da döngüler for, while ile başlar ancak end ile bitmez. 

Bunun yerine, satırların başlangıçları aynı hizada olacak şekilde girinti (indent) yapılır. 

#### 02.1.1- For

Değişkenlerin sırayla işleme alınması, tekrarlı işlemlere döngü denmektedir. 

Tipik döngüler, bir dizin içindeki elemanlar üzerinden olmaktadır. 

Döngüler başladıktan sonra istenen şartların yerine gelmesi halinde sonuna kadar kalmadan tamamlanabilir.

In [95]:
dongu_listesi = [1,2,3,4,5,6,7,8,9,10]

for i in dongu_listesi:
    print(i)


1
2
3
4
5
6
7
8
9
10


In [94]:
dongu_listesi = [10,20,30,40,50,60,70,80,90,100]

for i,j in enumerate( dongu_listesi ) :
    print(i,j)


0 10
1 20
2 30
3 40
4 50
5 60
6 70
7 80
8 90
9 100


- Listeleri gelişigüzel oluşturmak istersek Numpy paketini kullanabiliriz.

In [98]:
import numpy as np


In [100]:
listem = np.random.randn(100)

print( len(listem) )

100


In [101]:
for sayac , eleman in enumerate( listem[:5]):
    print(f" Acaba rakam ne olacak = {eleman}")

 Acaba rakam ne olacak = 2.5946354585563514
 Acaba rakam ne olacak = 0.562813458803684
 Acaba rakam ne olacak = -0.5175005200273235
 Acaba rakam ne olacak = 2.446327338367576
 Acaba rakam ne olacak = -0.19370146986827105


#### 02.1.2- While

Döngünün belli şartları sağlamasına bağlı olarak sürdürülmesidir.

In [105]:
limit_deger = 10
sayac = 0 

while sayac < limit_deger : 
    
    print( np.random.rand())
    
    sayac += 1

0.5956945609628893
0.7324074141577395
0.3163329707001873
0.43220461283207534
0.6457363233810871
0.06597990256407538
0.6171589481782578
0.49963427465738475
0.5196919592121761
0.403607057456732


#### 02.2- Karar verme

İşlemler sırasında değişkenlerin istenen şartları sağlaması veya sağlamaması halinde sürecin değişimini sağlar.

In [115]:
birinci_veri = 20
ikinci_veri = 10

if birinci_veri > ikinci_veri:
    
    print( f"{birinci_veri}, {ikinci_veri}'den büyüktür")
    
    # yeni bir değişken yaratalım
    
    yeni_veri = birinci_veri + ikinci_veri 
    
    print( yeni_veri)    
    

20, 10'den büyüktür
30


* Peki birden fazla karar verme söz konusu olamaz mı?

In [120]:
birinci_veri = 50
ikinci_veri = 10
ucuncu_veri = 40

if birinci_veri > ikinci_veri:
    
    print( f"{birinci_veri}, {ikinci_veri}'den büyüktür")
    
elif birinci_veri > ucuncu_veri:
    
    print( f"{birinci_veri}, {ucuncu_veri}'den büyüktür")
    

50, 10'den büyüktür


- Peki birden fazla durum söz konusu olamaz mı?

In [125]:
birinci_veri , ikinci_veri , ucuncu_veri = 50, 60 , 40

if birinci_veri > ikinci_veri:
    
    print( f"{birinci_veri}, {ikinci_veri}'den büyüktür")
    
elif  birinci_veri < ikinci_veri and birinci_veri > ucuncu_veri:
    
    print( f"{birinci_veri}, {ikinci_veri}'den küçük ve {ucuncu_veri}'den büyüktür")
    

50, 60'den küçük ve 40'den büyüktür


---

<img src="./resimler/10min.jpg">
---

**UFAK BİR HEYECAN YAŞAYALIM :**

_PROBLEM :_ Kendi belirlediğiniz bir dizindeki rakamların verilen iki rakama göre durumlarını belirtecek kodu yazınız. 

_SÜRE :_ 10dakika

_ÖDÜL :_ İlk bitirenle ders çıkışı kahve sohbeti


In [127]:
# Cevap


### 02.3- Matematik

Bilimsel ve mühendislik çalışmalarında, değişkenler ve dizinler üzerinde matematik işlemleri yapılmaktadır. Temel olarak dört işlem, ileri seviyede ise integral, türev vb. işlemler olmaktadır. 

#### 02.3.1- Temel işlemler

- Toplama, Çıkarma, Çarpma, Bölme

In [132]:
ali , veli = 45 , 55

print ( ali + veli )

print ( ali - veli )

print ( ali * veli )

print ( ali / veli )


100
-10
2475
0.8181818181818182


- Üssel ifadesi

In [135]:
print( ali * ali )

print( ali ** 2 )


2025
2025


- Yuvarlama : _Numpy nerede karşımıza çıkacak diyorduk :)_

In [138]:
print( np.floor( 1.4 ))

print( np.ceil( 1.4 ))

1.0
2.0


- Ondalık yuvarlama

In [142]:
round( 1.23456 , 2)

1.23

In [140]:
np.round( 1.23456 , 2)

1.23

#### 02.3.2- İleri işlemler

- Integral

In [177]:
from numpy import random

listem = [11,22,33,44] 

from scipy import integrate

print( integrate.trapz( listem))


82.5


- Yığışımlı Integral

In [176]:
from numpy import random

listem = [11,22,33,44] 

from scipy import integrate

print( integrate.cumtrapz( listem))


[16.5 44.  82.5]


- Farklar

In [191]:
listem = [21 , 3 , 5 , 4, 99]

import numpy as np

print ( np.diff( listem ) )


[-18   2  -1  95]


#### 02.4 Fonksiyonlar

İşlemler dizisini bir tanım altına almaktır. 

Pratik olarak bilimsel çalışmalarda, üretilen tüm algoritmaların bir fonksiyon haline getirilmesi stratejisi önerilmektedir. 

In [193]:
def eleman_secimi( liste_verilen , eleman_secilen):
    
    secelim = liste_verilen[ eleman_secilen]
    
    return(secelim)

In [194]:
bunebe = eleman_secimi( [1,"a",3,4,"he"] , 3 )

print( bunebe)

4


<img src="./resimler/1-basit_kiriş.png"> 


In [199]:
def basit_kiris( q , L):
    
    W =  ( q * L)
    
    v = 0.5 * W
    
    return( v)

basit_kiris( 10 , 5 )

25.0

---
<img src="./resimler/2-basit_kiriş_yamuk_yuk.png">

**UFAK BİR HEYECAN YAŞAYALIM :**

_PROBLEM :_ Verilen sistemin mesnet reaksiyonlarını hesaplayan fonksiyonu yazınız. 

_SÜRE :_ 10dakika

_ÖDÜL :_ İlk bitirenle ders çıkışı kahve + tatlı sohbeti


#### 02.5 Fonksiyoneller

İçiçe geçmiş fonksiyonlardır.

In [210]:
def bolme_islemi( a , b ):
    return( yuvarlama_programi(  a / b)) 

def yuvarlama_programi( a ) :
    return( round(a , 4) )

print( bolme_islemi(9 , 4.333) )


2.0771


---
<img src="./resimler/3-basit_kiriş_yamuk_yuk.png">

**UFAK BİR HEYECAN YAŞAYALIM :**

_PROBLEM :_ Verilen sistemde yükün değiştiği kesitlerdeki en büyük normal gerilmeyi hesaplayan programı geliştiriniz. 

_HATIRLATMA :_ $\sigma_n = \frac{M\times y}{I} $

_SÜRE :_ 20 dakika

_ÖDÜL :_ İlk bitirenle ders çıkışı kahve + tatlı sohbeti


#### 02.6 Matrisler
Python, MATLAB gibi değildir. Değişkenleri bir Matris gibi düşünmez. 

Bu sebeple MATLAB'de alışılan yaklaşım ve notasyondan farklı bir durum vardır. 

Her ne kadar Numpy içinde "matrix" diye bir sınıf bulunuyor olsa da gelecekte iptal edilecektir. 

Bundan dolayı, numpy içindeki "array" sınıfını kullanmayı önermekteyiz. 

#### 02.6.1 Çok boyutlu dizin = Matris işlemleri :)

Her ne kadar matematiksel olarak matris olsa da terminolojik olarak çok boyutlu dizin denmektedir. 

- Matris yaratma

In [5]:
import numpy as np

matris_1d = np.array([[1,2]])

print( matris_1d )

[[1 2]]


In [36]:
import numpy as np

matris_2d = np.array([[1,2] , [3,4]])

print( matris_2d )


[[1 2]
 [3 4]]


- Belirli matris yaratma

In [31]:
matris_1d_range = np.arange( 10 )

print( matris_1d_range)


[0 1 2 3 4 5 6 7 8 9]


In [58]:
matris_sifirlar = np.zeros(5)

print( matris_sifirlar)


[0. 0. 0. 0. 0.]


In [43]:
matris_birler = np.ones(5)

print( matris_birler)


[1. 1. 1. 1. 1.]


_Siz cevaplayın_

In [46]:
matris_ikiler = ????????

print( matris_ikiler)


[2. 2. 2. 2. 2.]


- Birim Matris yaratımı

In [80]:
matris_birim = np.eye(3)

print(matris_birim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- Köşegen Matris Yaratımı

In [83]:
matris_diagonal = np.diag([1,2,3,4])

print( matris_diagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


- Yeniden dizme

In [33]:
matris_1d_range_2boyut = matris_1d_range.reshape(5,2)

print( matris_1d_range_2boyut)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- Matris boyutlarının gösterimi

In [40]:
matris_1d_range_2boyut.shape 

(5, 2)

- Eleman sayısını gösterme

In [41]:
matris_1d_range_2boyut.size

10

#### 02.6.2 Matris Erişim

- Bir boyutlu matris erişim

In [47]:
matrisim = np.arange(1,100,10)

In [49]:
matrisim[:]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [50]:
matrisim[1]

11

- İki boyutlu matris erişim

In [57]:
matrisim_2b = np.array([[1,3,5] , [2,4,6] , [3,5,7]])

print( matrisim_2b)


[[1 3 5]
 [2 4 6]
 [3 5 7]]


In [55]:
matrisim_2b[:,0]

array([1, 2, 3])

In [56]:
matrisim_2b[:2  , 1 ]

array([3, 4])

- Matris güncelleme

In [59]:
matrisim_2b[1,1] = 100
print(matrisim_2b)

[[  1   3   5]
 [  2 100   6]
 [  3   5   7]]


#### 02.6.3 Matris Lineer Cebir İşlemleri

- Transpoze alma

In [68]:
matrisim_2b.transpose()

array([[  1,   2,   3],
       [  3, 100,   5],
       [  5,   6,   7]])

- Tersini alma

In [70]:
np.linalg.inv( matrisim_2b )

array([[-0.87239583, -0.00520833,  0.62760417],
       [-0.00520833,  0.01041667, -0.00520833],
       [ 0.37760417, -0.00520833, -0.12239583]])

- Toplama İşlemi

In [86]:
birinci_matris = np.array([[1,9] , [0,10]])
ikinci_matris = np.array([[5,4] , [2,7]])

sonuc = np.add( birinci_matris , ikinci_matris )

print( sonuc)


[[ 6 13]
 [ 2 17]]


- Çıkarma İşlemi

In [85]:
birinci_matris = np.array([[1,9] , [0,10]])
ikinci_matris = np.array([[5,4] , [2,7]])

sonuc = np.subtract(birinci_matris , ikinci_matris)

print( sonuc)


[[-4  5]
 [-2  3]]


- Çarpma İşlemi


In [88]:
birinci_matris = np.array([[1,9] , [0,10]])
ikinci_matris = np.array([[5,4] , [2,7]])

sonuc = np.multiply(birinci_matris , ikinci_matris )

print( sonuc)


[[ 5 36]
 [ 0 70]]


- Bölme İşlemi


In [89]:
birinci_matris = np.array([[1,9] , [0,10]])
ikinci_matris = np.array([[5,4] , [2,7]])

sonuc = np.divide(birinci_matris , ikinci_matris )

print( sonuc)


[[0.2        2.25      ]
 [0.         1.42857143]]


- Matris çarpım işlemi

In [81]:
birinci_matris = np.array([[1,9] , [0,10]])
ikinci_matris = np.array([[5,4] , [2,7]])

sonuc = np.dot(birinci_matris , ikinci_matris)

print( sonuc)


[[23 67]
 [20 70]]


- Bölme İşlemi

In [82]:
birinci_matris = np.array([[1,9] , [0,10]])
ikinci_matris = np.array([[5,4] , [2,7]])

sonuc = np.divide(birinci_matris , ikinci_matris)

print( sonuc)


[[0.2        2.25      ]
 [0.         1.42857143]]


- Determinant

In [94]:
matrisim =  np.array([[1,2,3,4],
                      [10,11,12,2],
                      [3,4,5,6],
                      [2,1,4,5]])

np.linalg.det( matrisim )

88.00000000000003

### 02.7- İstatistik

#### 02.7.1- Temel istatistikler 

- En büyük, küçük

In [104]:
matrisim =  np.array([[1,2,3,4],
                      [10,11,12,2],
                      [3,4,5,6],
                      [2,1,4,5]])

print( matrisim.max() ) 
print( matrisim.min() ) 

12
1


- Ortalama değer ve Standart Sapma

In [103]:
matrisim =  np.array([[1,2,3,4],
                      [10,11,12,2],
                      [3,4,5,6],
                      [2,1,4,5]])

print( matrisim[0,:].mean() )

print( matrisim[0,:].std() )


2.5
1.118033988749895


---

_AAD: Programlamada ikinci dersin sonu_

---