# BİR VEKTÖRÜ ÖZEL TABAN VEKTÖRLERİ KULLANARAK BİRLEŞENLERİNE AYIRMAK

Bu uygulamada bir vektörü sistem özdeğer vekörlerini kullanarak birleşenlerine ayıracağız. Böylesi bir işlemin yapılabilmesi için özdeğer vektörleri kullanılan sistemin serbestlik derecesi ile parçalanacak olan vektörün boyutunun aynı olması gerekir.

In [4]:
#Parçalanacak olan vektör
import numpy as np
u=np.array([1,1,0])
u

array([1, 1, 0])

In [3]:
u

array([1, 1, 0])


Şimdi parçalamada kullanacağımız özdeğer vektörlere sahip olan sistemi tanımlayalım

In [9]:
k=48e6
m=30000

M=np.array([[m, 0, 0],
            [0, m, 0],
            [0, 0, m]])

dof=M.shape[0] 

K=np.array([[2*k,-k, 0],
            [-k, 2*k, -k],
            [0, -k, k]])

In [10]:
K

array([[ 96000000., -48000000.,         0.],
       [-48000000.,  96000000., -48000000.],
       [        0., -48000000.,  48000000.]])

In [11]:
M

array([[30000,     0,     0],
       [    0, 30000,     0],
       [    0,     0, 30000]])

Sistemin özdeğer vektörlerini ve özdeğerlerini hesaplayalım. BU uygulamada kullanılmayacak olmakla beraber
sistem özdeğerlerinin bizim sistemim frekanslarımızın kareleri olduğunu hatırlatalım.

In [13]:
As = np.dot( np.linalg.inv(M) , K)

V,D = np.linalg.eigh(As) #Özdeğerler ve özdeğer vektörleri

w = [np.sqrt(item) for item in V] #Sistemin frekansları
T = [2*np.pi/item for item in w]  #Sistemin periyotları

In [14]:
V

array([ 316.89962271, 2487.93301134, 5195.16736595])

In [15]:
D

array([[-0.32798528,  0.73697623, -0.59100905],
       [-0.59100905,  0.32798528,  0.73697623],
       [-0.73697623, -0.59100905, -0.32798528]])

In [16]:
w

[17.80167471650516, 49.879184148698684, 72.07750943219354]

In [17]:
T

[0.35295473079024475, 0.12596808497204562, 0.08717261954077996]

In [20]:
L = np.zeros( dof )
up = np.zeros((dof,dof))
ur = np.zeros(dof)
T_D=np.transpose(D)
PMP=np.dot(np.dot(T_D,M),D)

BU BASAMAKTA VEKTÖRÜ BİLEŞENLERİNE AYIRINIZ, up

BİRLEŞENLERİN TOPLAMININ ORJİNAL VEKTÖRE KARŞILIK GELİĞ GELMEDİĞİNİ KONTROL EDİNİZ, ur

In [26]:
up

array([[ 0.30141661,  0.78485132, -0.08626792],
       [ 0.54313396,  0.3492917 ,  0.10757434],
       [ 0.67727697, -0.62940189, -0.04787509]])

Kontrol amacıyla bileşenleri birleştirdiğimizde aynı vektöre ulaşmamız lazım

In [27]:
ur

array([1.00000000e+00, 1.00000000e+00, 3.46944695e-17])