# YAPI DİNAMİĞİ ÇALIŞTAYI 2019
### İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ 9-19 EYLÜL 2019
#### Hazırlayan : Ahmet Anıl Dindar (adindar@gtu.edu.tr)

---

## __03. Python'da Veri Okuma/Yazma :__ 

Bilimsel çalışmalarda üretilen veya kullanılacak verinin saklanması, paylaşılması için okuma/yazma işlemleri gereklidir.

### __03.1- ASCII :__ 

İnsanların okuyabileceği formatta hazırlanmış dosyalardır.

### __03.2- BINARY :__ 

Bilgisayaların okuyabileceği formatta hazırlanmış dosyalardır.

### __03.3- OPEN :__ 

Her iki dosya türünü de okuma/yazma istersek, en pratik yol "open" komutudur. 

### 03.3.1- Okuma

Okuma amacıyla kullanılır. 

- ASCII okuma

In [11]:
dosya = open( "acc01_4063e0_20190801_0600e.txt",  "r")

In [12]:
icerik = dosya.readlines()

In [13]:
type(icerik)

list

In [14]:
icerik[:5]

['_ACC01  4063E0  2019 08 01 06 00 00  200\n',
 '       2325\n',
 '       2299\n',
 '       2256\n',
 '       2220\n']

In [16]:
dosya.close()

- Bu dosya üzerinde işlem yapınız, örneğin yazı tipindeki elemanları integer formatında işlem yapılabilir hale getiriniz.

- BINARY okuma

In [17]:
dosya = open( "acc01_4063e0_20190801_0600e.gcf",  "rb")

In [18]:
icerik = dosya.readlines()

In [19]:
type(icerik)

list

In [20]:
icerik[:5]

[b'\x85\t\x11\xc1\x0en\xe6\xa8T\xc2T`v\xc8\x02\xc8\x00\x00\t\x15\x00\x00\xff\xe6\xff\xd5\xff\xdc\x00d\xff\xed\xff\x9d\x00 \x004\x00"\xff\x9a\x00H\x00\x07\xff\xdf\xff\xdb\x005\x00E\xff\xba\xff\xea\xff\xef\x00\x07\xff\xf4\x00\x13\x00L\xff\xcb\xff\xcd\x00)\x00.\xff\xde\xff\xdb\x00%\xff\xfe\xff\xfa\xff\xfa\x00\r\xff\xfa\xff\xe8\xff\xfd\x00!\x00\x16\xff\xeb\xff\xea\x00\x06\xff\xed\x00\t\x00\x13\x00\x07\x00\x11\x00\x06\xff\xd7\xff\xe2\x00#\x00\x1d\x00\x0c\xff\xc0\x00\x1f\x00$\xff\xdd\xff\xb7\x00"\x00X\xff\xc6\xff\xde\x00&\x00\x1e\xff\xe0\xff\xf9\x00#\xff\xfb\xff\xd1\xff\xea\x00)\x000\xff\xfa\xff\xbd\x00&\x00\x17\xff\xc8\xff\xea\x00K\x00 \xff\xac\xff\xff\x004\xff\xf6\xff\xc5\x00\x1a\x00F\xff\xc6\x00\x05\xff\xff\xff\xe8\x00\'\x00\x15\x00*\xff\xa4\xff\xd5\x00\n',
 b'\x003\x00\x07\xff\xf8\x00\x1d\xff\xfd\xff\x9a\x00\'\x00,\x00\x0c\x00\x10\xff\xf3\xff\xe2\xff\xfe\x00.\xff\xb9\xff\xe5\x00D\x007\xff\xc4\xff\xff\x00@\xff\xcd\xff\xb3\xff\xfd\x00<\x00\'\xff\xd8\x00\x0b\x00"\x00\x02\xff\xaf\xff\xfe\x00

In [21]:
dosya.close()

- ASCII okuma ve işlem yapma

In [ ]:
with open( "acc01_4063e0_20190801_0600e.txt",  "r") as dosya :
    
    for satir in dosya.readlines():
        
        print(satir)

### 03.3.2- Yazma

Verileri dosyaya yazma amacıyla kullanılır. 

In [25]:
import numpy as np
listem = [ np.random.randn() for item in range(10)]

print( listem )


[-0.2965819842880848, -0.749426059303648, 0.9950813354208898, -1.4715336106756207, 0.5340299308182604, -0.33909302640759315, -0.2371604389560698, 0.0842704040092735, -0.8376988516454047, 0.453560320832434]


In [27]:
with open("yeni bir dosya yaziyorum.txt" , "w") as dosya:
    for satir in listem:
        dosya.write( str( satir ) + "\n")
        

- Veya daha kontrollü olması için zengin yazı kullanılır

In [32]:
with open("yeni bir dosya yaziyorum 2.txt" , "w") as dosya:
    for satir in listem:
        dosya.write( f"{satir} , {satir*2} \n")
        

- Peki bu \n ifadesini yazmazsak ne olur?

### __03.4- NUMPY :__ 

Belli bir yapısı bulunan verileri nasıl okur/yazarız

Bunun kolay yolu pek tabi ki Numpy paketidir.

#### 03.4.1- Okuma

In [34]:
import numpy as np

verilerim = np.loadtxt( "yeni bir dosya yaziyorum.txt" )

type(verilerim)

numpy.ndarray

In [35]:
verilerim

array([-0.29658198, -0.74942606,  0.99508134, -1.47153361,  0.53402993,
       -0.33909303, -0.23716044,  0.0842704 , -0.83769885,  0.45356032])

In [40]:
import numpy as np

verilerim_2 = np.loadtxt( "yeni bir dosya yaziyorum 2.txt" , delimiter = ",")

type(verilerim_2)

numpy.ndarray

In [39]:
verilerim_2

array([[-0.29658198, -0.59316397],
       [-0.74942606, -1.49885212],
       [ 0.99508134,  1.99016267],
       [-1.47153361, -2.94306722],
       [ 0.53402993,  1.06805986],
       [-0.33909303, -0.67818605],
       [-0.23716044, -0.47432088],
       [ 0.0842704 ,  0.16854081],
       [-0.83769885, -1.6753977 ],
       [ 0.45356032,  0.90712064]])

- Peki text dosyasında bir başlık varsa? Örneğin ivme kaydı dosyası

#### 03.4.2- Yazma

In [44]:
listem =  [ np.random.randn() for item in range(10)] 

np.savetxt ( "veri yazma.csv", [ listem ] , delimiter=",")


- Peki delimiter farklı bir şey olabilir mi, mesela tab?

- Peki birden fazla liste yazılmak istenirse?

In [46]:
listem =  [ np.random.randn() for item in range(10)] 

np.savetxt ( "veri yazma 2.csv",  ??????? , delimiter=",")


SyntaxError: invalid syntax (<ipython-input-46-777a8dc2c570>, line 3)

### __03.5- Pandas:__

Pandas çok güçlü bir veri okuma aracıdır. Çok mucizeler yaratır. Veri tabanı yapısına benzer bir yapısı vardır. 

#### 03.5.1- Okuma

Pandas, binary, ascii ve hatta sıkıştırılmış dosyaları dahi okur. 

İlk satırı başlık kabul eder. 

In [48]:
import pandas as pd

veri_df = pd.read_csv( "ilk pandas okuma.txt")

print( type( veri_df ))

<class 'pandas.core.frame.DataFrame'>


In [49]:
veri_df

kolon1  kolon2  kolon3
0       1       2       3
1      10      20      30
2     100     300     300

- Şimdi biraz tembellik edelim

In [50]:
veri_df.describe()

kolon1      kolon2      kolon3
count    3.000000    3.000000    3.000000
mean    37.000000  107.333333  111.000000
std     54.744863  167.096778  164.234588
min      1.000000    2.000000    3.000000
25%      5.500000   11.000000   16.500000
50%     10.000000   20.000000   30.000000
75%     55.000000  160.000000  165.000000
max    100.000000  300.000000  300.000000

- Peki başka özellikler

#### 03.5.2- Yazma

Pandas, veri yazmada da mucizeler yaratır

In [54]:
sozluk_hatirla = {"ilki":[1,2,3] , "ikincisi":[10,20,30]}

sozluk_df = pd.DataFrame( sozluk_hatirla)

sozluk_df

ilki  ikincisi
0     1        10
1     2        20
2     3        30

In [55]:
sozluk_df.to_csv("ikinci panda yazmam.txt")

### __03.6- Pickle:__

Eğer üretilen veya okunan verileri yani değişkenleri daha sonra kullanmak üzere saklamak istiyorsanız "turşu" yapımı işinize yarayacaktır :)

In [68]:
veri_1 = [1,11,21,31,41]
veri_2 = ["adem", "madem" , "badem"]

import pickle

dosya_ismi = open("ilk tursu.pkl" , "wb") 
pickle.dump((veri_1,veri_2) , dosya_ismi )
dosya_ismi.close()

In [67]:
d = open("ilk tursu.pkl" , "rb")
vv = pickle.load(d)
d.close()

In [69]:
type(vv)

tuple

In [70]:
vv

([1, 11, 21, 31, 41], ['adem', 'madem', 'badem'])

### __03.7- MAT dosyalarını okuma :__ 

In [1]:
import scipy.io
mat = scipy.io.loadmat('IdResults.mat')

In [5]:
type(mat)

dict

In [6]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'phi', 'Frequencies', 'Fp', 's1'])

In [4]:
mat["phi"]

array([[-5.42955901e-02+3.71605993e-17j, -3.40551166e-02+1.52704986e-17j],
       [-6.71222944e-02+7.13290493e-03j, -4.37361927e-02+3.39666292e-03j],
       [-5.25653547e-03-7.48580828e-03j,  5.12664765e-02-7.09038612e-04j],
       [ 1.93585913e-02+7.84105453e-03j,  1.60026217e-03-3.24258784e-04j],
       [-4.04083446e-01+2.18546219e-01j, -2.45882596e-01-2.31662766e-01j],
       [-4.03383389e-01+2.03065196e-01j, -1.45179030e-01-4.86197103e-01j],
       [-3.66600407e-01+2.04416369e-01j, -2.01538155e-01-2.01515078e-01j],
       [ 1.71544740e-02-2.35706790e-02j,  2.00106059e-01+5.42207747e-01j],
       [ 5.38263952e-02-4.40759291e-02j,  2.73287469e-01+2.30013412e-01j],
       [ 3.19291373e-01-1.66321226e-01j, -3.13831448e-03+2.36596365e-01j],
       [ 3.12683122e-01-1.73423676e-01j,  2.91001875e-02+1.11107915e-01j],
       [ 2.86929843e-02+1.79853047e-03j, -1.85699692e-02+1.84576853e-02j],
       [-2.01258229e-02+8.51657377e-02j,  2.55484966e-04+2.35069116e-02j],
       [ 3.17424279e-01-1

---

_AAD: Programlamada üçüncü dersin sonu_

---